from mautrix.util.async_db import Connection, Scheme

from . import upgrade_table


@upgrade_table.register(description="Add index to reaction table")
async def upgrade_v5(conn: Connection, scheme: Scheme):
    if scheme != Scheme.SQLITE:
        await conn.execute('ALTER TABLE reaction ADD COLUMN "index" INTEGER')

        # Give everything an index based on row number
        await conn.execute(
            """
            UPDATE reaction
               SET "index" = t.rownum
              FROM (SELECT mxid, mx_room, ROW_NUMBER() OVER () AS rownum
                      FROM reaction) t
             WHERE reaction.mxid = t.mxid
               AND reaction.mx_room = t.mx_room
            """
        )

        # Make the new column SERIAL
        await conn.execute('ALTER TABLE reaction ALTER COLUMN "index" SET NOT NULL')
        await conn.execute(
            """
            ALTER TABLE reaction ALTER COLUMN "index" ADD GENERATED BY DEFAULT AS IDENTITY
            """
        )
    else:
        await conn.execute(
            """
            CREATE TABLE reaction_v5 (
                rowid           INTEGER PRIMARY KEY AUTOINCREMENT,
                mxid            TEXT,
                mx_room         TEXT,
                li_message_urn  TEXT,
                li_receiver_urn TEXT,
                li_sender_urn   TEXT,
                reaction        TEXT,

                UNIQUE (mxid, mx_room)
            )
            """
        )
        await conn.execute(
            """
            INSERT INTO reaction_v5 (
                rowid, mxid, mx_room, li_message_urn, li_receiver_urn, reaction
            )
            SELECT rowid, mxid, mx_room, li_message_urn, li_receiver_urn, reaction FROM reaction
            """
        )
        await conn.execute("DROP TABLE reaction")
        await conn.execute("ALTER TABLE reaction_v5 RENAME TO reaction")
